### ISSUE TITLE
wk init show syntax error on ubuntu with both python 2 and 3

### ISSUE THREAD

**Issue by oren** [ludovicchabant/Wikked#2]
Steps to reproduce:

1.  pip install wikked -U
1. wk init

```
Traceback (most recent call last):
  File "/home/oren/.local/bin/wk", line 7, in <module>
    from wikked.witch import real_main
  File "/home/oren/.local/lib/python2.7/site-packages/wikked/witch.py", line 8, in <module>
    from wikked.utils import find_wiki_root
  File "/home/oren/.local/lib/python2.7/site-packages/wikked/utils.py", line 58
    def get_absolute_url(base_url, url, *, force_endpoint=None, quote=False):
                                         ^
SyntaxError: invalid syntax
```

I am on Ubuntu 16.04 that comes with python2. I had to install python3 and i also added an alias in my .bash_aliases to force using python3: `alias python='python3'`.

```
python2.7 --version
Python 2.7.12

python3 --version
Python 3.5.2
```

**Comment by ludovicchabant** [comment]
Hi! Most likely, your version of `pip` is the one linked to Python 2.7. Type `pip --version` and see what it says at the end of the line (it should show the version of Python).

Often, the Python 3 install aliases its own `pip` to `pip3`, so try to do:

```
pip3 install wikked
```

**Comment by oren** [comment]
Thanks! 

now I am getting a different error
```
wk init mywiki
Initializing new wiki at: /home/oren/p/tmp/mywiki
Creating Mercurial repository at: /home/oren/p/tmp/mywiki
[Errno 2] No such file or directory: 'hg'
```

and the mywiki folder is empty

**Comment by oragnu** [comment]
I get the same error (on Windows) because I do not have hg installed.

Is there a way to configure "wk init" to use git instead? It is stated that git is supported, so I suspect I am just missing something.

**Comment by ludovicchabant** [comment]
I just added a warning if Mercurial isn't installed, along with a note about running `wk init --git` to use Git instead. Thanks!
